### ISSUE TITLE
Task #2: Module structure, user manipulation, command flow improvements

### ISSUE THREAD

**Issue by livercat** [iankusheva/idbetterbecoding#2]
1) Поменять структуру проекта: сделать директорию для sample.py и добавить туда __init__.py (и рассказать зачем), переименовать его во что-то более понятное (db.py?).
2) Сделать методы (и CLI-комманды) для добавления и удаления пользователей. Не забыть обработать ошибки логики.
3) После выполнения комманды не выходить из программы, а давать возможность ввести новую комманду. Добавить метод quit.

Про пункт (3) не уверен, насколько легко реализуем click'ом. Но выглядит как довольно распространенный юзкейс, наверняка что-нибудь должно нагуглиться.

**Comment by iankusheva** [comment]
pullreq https://github.com/iankusheva/idbetterbecoding/pull/3
