### ISSUE TITLE
Task #3: Expand DB

### ISSUE THREAD

**Issue by livercat** [iankusheva/idbetterbecoding#4]
Сделать в базе таблички для того, чтобы юзеры могли хранить любимые книжки. Проектировать таблички с учетом того, чтобы можно было показать:
a) Все любимые книги юзера.
b) Рейтинги топовых авторов и книг (отдельно).
c) Все книги определенного автора, с количеством юзеров которые любят каждую книжку.
При этом данные дублироваться в разных табличках не должны.

Вынести весь SQL для создания базы в отдельный файл.

**Comment by iankusheva** [comment]
1. Наполнение всех разных табличек должно происходить через один и тот же уже написанный метод? или я вообще могу это руками сделать?
2. Непонятно про дублирование данных :( Если у меня будет табличка связи юзеров с их книгами, дублирование айдишников это же не дублирование?
3. a-c) вываливать все подряд в какой-то момент или тоже спрашивать у пользователя какую именно инфу он хочет посмотреть?

**Comment by livercat** [comment]
1) Пока что только таблички, без наполнения. Это будет следующий таск.
2) Да, это нормально. Даже нормально если где-то будет дублирование каунтеров, если это обоснованно.
3) Тоже в следующем таске.

**Comment by iankusheva** [comment]
ааааа изи бризи. или нет)

**Comment by iankusheva** [comment]
![image](https://user-images.githubusercontent.com/7661388/31490352-4e2d6f6c-af4c-11e7-9201-2ecbf54351e5.png)

**Comment by livercat** [comment]
Выглядит хорошо.

**Comment by iankusheva** [comment]
на самом деле это был скриншот отчаяния, чтобы не потерять, зачем ты так быстро смотришь!

**Comment by iankusheva** [comment]
чувствую серьезную потребность почитать учебник по sql
![image](https://user-images.githubusercontent.com/7661388/31491308-8e6038aa-af4f-11e7-9d75-aec69f7472b5.png)
(это было a))

**Comment by livercat** [comment]
:)
Не используй format для SQL-запросов, это небезопасно:
https://docs.python.org/3.6/library/sqlite3.html

> Usually your SQL operations will need to use values from Python variables. You shouldn’t assemble your query using Python’s string operations because doing so is insecure; it makes your program vulnerable to an SQL injection attack (see https://xkcd.com/327/ for humorous example of what can go wrong).

> Instead, use the DB-API’s parameter substitution. Put ? as a placeholder wherever you want to use a value, and then provide a tuple of values as the second argument to the cursor’s execute() method

**Comment by iankusheva** [comment]
fuck

**Comment by iankusheva** [comment]
Окей, я оставила пока попытки стать чемпионом SQL, просто сделала по таску
https://github.com/iankusheva/idbetterbecoding/pull/7
