### ISSUE TITLE
Task #4: DB data upload via JSON

### ISSUE THREAD

**Issue by livercat** [iankusheva/idbetterbecoding#5]
Сделать методы, которые принимают JSON-строчку и сохраняют информацию в базу.
1) Добавить книгу (если автора нет, то добавить)
2) Добавить список любимых книг юзера. Повторные игнорировать. Если книги и/или автора нет, то добавить.

**Comment by livercat** [comment]
Все это сохраняется в books.db / authors.db, которые автоматически создаются если их нет. Юзеров хранить в users.db, юзера тоже автоматом добавлять если его нет.

**Comment by iankusheva** [comment]
так, то есть мой SQL неправильный весь? у меня все собиралось в одну дб в разные таблички.

я могу по-нубовски хранить джейсон в модуле как глобальную переменную или мне откуда-нибудь из файла выгружать?

**Comment by iankusheva** [comment]
жду с нетерпением того дня, когда перестану быть тупой((🌚

**Comment by iankusheva** [comment]
а при запуске скрипта должно быть указано, какой именно метод вызывать или по json надо догадатьсЯ?

**Comment by livercat** [comment]
> так, то есть мой SQL неправильный весь? у меня все собиралось в одну дб в разные таблички.

SQL от количества файлов с табличками не зависит - просто будешь открывать разные файлики в разных методах.

> я могу по-нубовски хранить джейсон в модуле как глобальную переменную или мне откуда-нибудь из файла выгружать?

Не очень понял. Ты будешь вызывать скрипт так (ну не совсем так, кавычки наверное экранировать надо будет):
python3 run_cli.py add_book {"book": "you are smart", "author": "don't forget it"}

> а при запуске скрипта должно быть указано, какой именно метод вызывать или по json надо догадатьсЯ?

Да, должно быть указано

**Comment by iankusheva** [comment]
меня смущает, что "SQL doesn't support cross database referential integrity". как тогда связать разные дб без дублирования информации?
(я пока не оставила попытки это нагуглить, просто риторический вопрос)

**Comment by livercat** [comment]
Да, действительно. Значит одна база :)

**Comment by iankusheva** [comment]
у меня перед первым запуском скрипта база должна не существовать и ее надо создавать?

**Comment by livercat** [comment]
Да, заодно можно убрать методы для ручного создания базы и юзеров.

**Comment by livercat** [comment]
Пусть будет какое-нибудь по умолчанию зашитое имя файла db, но в каждый торчащий наружу метод можно будет передать аргумент типа --db="other_file.db", чтобы взять его имя (нужно будет для тестов, в таске #6 ).
Если такого файла нет, молча создавать; если есть, использовать его.
